import "./css/style.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "IFA",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className="scroll-smooth">
//       <body
//         className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
//       >
//         <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className="bg-gray-50 font-inter tracking-tight text-gray-900 antialiased"
        // className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}

      >
        <div className="flex min-h-screen flex-col overflow-auto supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
      </body>
    </html>
  );
}
